import img1 from '../../public/img/마드레드.jpg'
import img2 from '../../public/img/마테라컵케잌.jpg'
import img3 from '../../public/img/버터롤.jpg'
import img4 from '../../public/img/버터톱식빵.jpg'
import img5 from '../../public/img/베이글.jpg'
import img6 from '../../public/img/브라우니.jpg'
import img7 from '../../public/img/사과파이.jpg'
import img8 from '../../public/img/소시지빵.jpg'
import img9 from '../../public/img/쇼트브레드.jpg'
import img10 from '../../public/img/스위트롤.jpg'
import img11 from '../../public/img/식빵.jpg'
import img12 from '../../public/img/타르트.jpg'
import img13 from '../../public/img/크림빵.jpg'
import img14 from '../../public/img/우유식빵.jpg'




export const cources = [
    {
        id: 'l1',
        title: '초코롤 케이크',
        description: '초코롤 케이크 강의 입니다.',
        image: img11,
        price: 1000,
        category: ['제과'],
        method: ['공립법'],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l2',
        title: '치즈 케이크',
        description: '치즈 케이크 강의 입니다.',
        image: img11,
        price: 1500,
        category: ['제과'],
        method: ['크림법','별립법'],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l3',
        title: '소시지빵',
        description: '소시지빵 강의 입니다.',
        image: img8,
        price: 1200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l4',
        title: '슈',
        description: '슈 강의 입니다.',
        image: img2,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l5',
        title: '파운드 케이크',
        description: '파운드 케이크 강의 입니다.',
        image: img11,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l6',
        title: '통밀빵',
        description: '통밀빵 강의 입니다.',
        image: img4,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l7',
        title: '버터롤',
        description: '버터롤 강의 입니다.',
        image: img11,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l8',
        title: '타르트',
        description: '타르트 강의 입니다.',
        image: img2,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l9',
        title: '크림빵',
        description: '크림빵 강의 입니다.',
        image: img14,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l10',
        title: '우유식빵',
        description: '우유식빵 강의 입니다.',
        image: img14,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l11',
        title: '과일 케이크',
        description: '초코롤 케이크 강의 입니다.',
        image: img11,
        price: 1000,
        category: ['제과'],
        method: ['크림법','별립법'],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l12',
        title: '버터톱 식빵',
        description: '버터톱 식빵 강의 입니다.',
        image: img11,
        price: 1500,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l13',
        title: '빵도우넛',
        description: '빵도우넛 강의 입니다.',
        image: img8,
        price: 1200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l14',
        title: '마들렌',
        description: '마들렌 강의 입니다.',
        image: img2,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l15',
        title: '마테라 컵케잌',
        description: '파운드 케이크 강의 입니다.',
        image: img2,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l16',
        title: '그리시리',
        description: '그리시리 강의 입니다.',
        image: img4,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l17',
        title: '모카빵',
        description: '모카빵 강의 입니다.',
        image: img11,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l18',
        title: '사과파이',
        description: '사과파이 강의 입니다.',
        image: img2,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l19',
        title: '브라우니',
        description: '브라우니 강의 입니다.',
        image: img14,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l20',
        title: '호밀빵',
        description: '호밀빵 강의 입니다.',
        image: img14,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l21',
        title: '베이글',
        description: '베이글 강의 입니다.',
        image: img11,
        price: 1000,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l22',
        title: '다쿠아즈',
        description: '다쿠아즈 강의 입니다.',
        image: img11,
        price: 1500,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l23',
        title: '쇼트브레드쿠키',
        description: '쇼트브레드쿠키 강의 입니다.',
        image: img8,
        price: 1200,
        category: ['제과'],
        method: ['크림법','수작업'],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l24',
        title: '옥수수 식빵',
        description: '옥수수 식빵 강의 입니다.',
        image: img2,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l25',
        title: '스위틑롤',
        description: '스위틑롤 강의 입니다.',
        image: img11,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l26',
        title: '버터 스폰지 케이크(공립법)',
        description: '버터 스폰지 케이크 강의 입니다.',
        image: img4,
        price: 2200,
        category: ['제과'],
        method: ['공립법'],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l27',
        title: '버터 스폰지 케이크(별립법)',
        description: '버터 스폰지 케이크 강의 입니다.',
        image: img11,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l28',
        title: '단과자빵(트위스트형)',
        description: '단과자빵 강의 입니다.',
        image: img2,
        price: 2200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l29',
        title: '식빵(비상스트레이트법)',
        description: '비상 식빵 강의 입니다.',
        image: img14,
        price: 2200,
        category: ['제빵'],
        method: ['비상','스트레이트'],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l30',
        title: '젤리롤 케잌(공립법)',
        description: '젤리롤 케잌(공립법) 강의 입니다.',
        image: img14,
        price: 2200,
        category: ['제빵'],
        method: ['공립법'],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l31',
        title: '소프트롤 케이크',
        description: '소프트롤 케이크 강의 입니다.',
        image: img11,
        price: 1000,
        category: ['제과'],
        method: ['별립법'],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l32',
        title: '풀먼 식빵',
        description: '풀먼 식빵 강의 입니다.',
        image: img11,
        price: 1500,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l33',
        title: '밤식빵',
        description: '밤식빵 강의 입니다.',
        image: img8,
        price: 1200,
        category: ['제빵'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
      {
        id: 'l34',
        title: '호두파이',
        description: '호두파이 강의 입니다.',
        image: img2,
        price: 2200,
        category: ['제과'],
        method: [],
        howto : {
          step1 : '',
          step2 : '',
          step3 : '',
          step4 : '',
          step5 : '',
          step6 : '',
          step7 : '',
          step8 : '',
          step9 : '',
          tip : '',
          refer : ''
        },
        fulltime : '',
        mytime : '',
        isPurchase: false,
        isFavorite: false
      },
]